import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { resolve, sep } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const target = resolve(root, 'supabase/functions/pupsik-api/generated');
if (!target.startsWith(root + sep))
  throw new Error('Build output outside project');
await rm(target, { recursive: true, force: true });
const packageLock = JSON.parse(
  await readFile(resolve(root, 'package-lock.json'), 'utf8')
);
const supabaseVersion =
  packageLock.packages['node_modules/@supabase/supabase-js'].version;

// Keep the existing API as the source of truth. Generate ESM for the Deno runtime.
for (const directory of ['api', 'lib']) {
  await mkdir(resolve(target, directory), { recursive: true });
  for (const filename of await readdir(resolve(root, directory))) {
    if (!filename.endsWith('.js') || filename === 'admin-session.js') continue;
    let source = await readFile(resolve(root, directory, filename), 'utf8');
    source = source.replace(/\r\n/g, '\n');
    const needsBuffer = /\bBuffer\b/.test(source);
    source = source.replace(
      /const\s+(\{[\s\S]*?\}|\w+)\s*=\s*require\('([^']+)'\);/g,
      (_, names, dependency) => {
        if (dependency === 'node:crypto') return '';
        const path =
          dependency === '@supabase/supabase-js'
            ? `npm:@supabase/supabase-js@${supabaseVersion}`
            : dependency === '../lib/admin-session.js'
              ? '../../admin-session.js'
              : dependency;
        return `import ${names} from '${path}';`;
      }
    );
    // Deno always supplies fetch; Node-only fallbacks must not enter the bundle.
    source = source.replace(
      /function resolveFetch\(\) \{[\s\S]*?\n\}\n/,
      'function resolveFetch() { return { fetch: globalThis.fetch }; }\n'
    );
    source = source.replace(/process\.env\[name\]/g, 'Deno.env.get(name)');
    source = source.replace(
      /process\.env\.([A-Z_0-9]+)/g,
      'Deno.env.get("$1")'
    );
    source = source.replace(/module\.exports = \{/g, 'export {');
    source = source.replace(/module\.exports = /g, 'export default ');
    source = source.replace(
      /(?<!function )\b(verifyAdminToken|issueAdminToken|verifyAdminRequest)\(/g,
      'await $1('
    );
    source = source.replace(
      /(?<!async )function (verifyAdminRequest|handleVerifyAdmin)\(/g,
      'async function $1('
    );
    if (filename === 'admin.js') {
      source = source.replace(
        'function createHistoryEtag(',
        'async function createHistoryEtag('
      );
      source = source.replace(
        "const hash = createHash('sha1').update(payload).digest('hex');",
        "const digest = await crypto.subtle.digest('SHA-1', new TextEncoder().encode(payload));\n  const hash = Array.from(new Uint8Array(digest), byte => byte.toString(16).padStart(2, '0')).join('');"
      );
      source = source.replace(
        'const etag = createHistoryEtag(items);',
        'const etag = await createHistoryEtag(items);'
      );
      source = source.replace(
        "'HTTP-Referer': 'https://pupsik-tv.vercel.app'",
        "'HTTP-Referer': 'https://mahoitz.github.io/PupsikTV/'"
      );
    }
    if (/\brequire\(|module\.exports|process\./.test(source)) {
      throw new Error(
        `Unsupported Node expression in ${directory}/${filename}`
      );
    }
    const prefix =
      '// Generated by npm run build:edge. Edit the original api/ or lib/ file.\n';
    await writeFile(
      resolve(target, directory, filename),
      prefix +
        (needsBuffer ? "import { Buffer } from 'node:buffer';\n" : '') +
        source
    );
  }
}
console.log('Generated Supabase API modules.');
