create table if not exists public.trailer_watchlist (
  id bigint generated by default as identity primary key,
  title text not null,
  youtube_url text not null,
  youtube_video_id varchar(32) not null,
  kinopoisk_id integer,
  year integer,
  poster text,
  status text not null default 'planned' check (status in ('planned', 'watched')),
  streamer_rating numeric(3, 1),
  watched_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists trailer_watchlist_status_idx
  on public.trailer_watchlist (status, created_at desc);

create index if not exists trailer_watchlist_kinopoisk_idx
  on public.trailer_watchlist (kinopoisk_id);

create or replace function public.set_trailer_watchlist_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trailer_watchlist_set_updated_at on public.trailer_watchlist;

create trigger trailer_watchlist_set_updated_at
before update on public.trailer_watchlist
for each row
execute function public.set_trailer_watchlist_updated_at();

alter table public.trailer_watchlist enable row level security;
