create table if not exists public.boosty_reviews (
  id bigint generated by default as identity primary key,
  title text not null,
  url text not null,
  image text,
  meta text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint boosty_reviews_url_key unique (url)
);

create index if not exists boosty_reviews_created_idx
  on public.boosty_reviews (created_at desc);

create or replace function public.set_boosty_reviews_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists boosty_reviews_set_updated_at on public.boosty_reviews;

create trigger boosty_reviews_set_updated_at
before update on public.boosty_reviews
for each row
execute function public.set_boosty_reviews_updated_at();

alter table public.boosty_reviews enable row level security;
