create table if not exists public.kinopoisk_actors (
  id bigint generated by default as identity primary key,
  kinopoisk_film_id integer not null,
  staff_id integer not null,
  actor_name text not null,
  poster_url text,
  profession_text text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint kinopoisk_actors_film_staff_key unique (kinopoisk_film_id, staff_id)
);

create index if not exists kinopoisk_actors_film_idx
  on public.kinopoisk_actors (kinopoisk_film_id);

create index if not exists kinopoisk_actors_name_idx
  on public.kinopoisk_actors (actor_name);

create or replace function public.set_kinopoisk_actors_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists kinopoisk_actors_set_updated_at on public.kinopoisk_actors;

create trigger kinopoisk_actors_set_updated_at
before update on public.kinopoisk_actors
for each row
execute function public.set_kinopoisk_actors_updated_at();

alter table public.kinopoisk_actors enable row level security;
